#'''Parameters'''#


# --- general --- #

minqual:    30


# --- filter_low_qual --- #

dedup:      False


# --- filter_adapters --- #

trim_exec: ''
trim_adapters: ''


# --- filter_host_reads --- #

use_host_filter:         True
host_reference_database: ''
