#'''Parameters'''#

ext: ''
conda_prefix: ''

# --- general --- #

minqual:    30


# --- filter_low_qual --- #

dedup:      False


# --- filter_adapters --- #

adapters: ''


# --- filter_host_reads --- #

use_host_filter:         'True'
host_ref_genome:         ''


# --- filter_seq_errors --- #

# Options (must choose one): 'bayeshammer', 'tadpole'
error_correction: 'tadpole'


# --- qc-option --- #

qc_dataviz: True
